const ALL_QUESTION_TYPES = [
  'MULTIPLE_CHOICE',
  'TRUE_FALSE_NG',
  'FILL_BLANK',
  'SHORT_ANSWER',
  'MATCHING',
  'MATCHING_HEADINGS',
  'SENTENCE_COMPLETION',
  'DIAGRAM_LABELING',
  'FORM_COMPLETION',
  'NOTE_COMPLETION',
  'TABLE_COMPLETION',
  'FLOW_CHART_COMPLETION',
  'SUMMARY_COMPLETION',
  'MAP_LABELING',
  'PLAN_LABELING',
  'WRITING_TASK1',
  'WRITING_TASK2',
  'SPEAKING_PART1',
  'SPEAKING_PART2',
  'SPEAKING_PART3',
];

const MODULE_TYPES = ['LISTENING', 'READING', 'WRITING', 'SPEAKING'];

const ALLOWED_BY_MODULE = {
  LISTENING: [
    'MULTIPLE_CHOICE',
    'MATCHING',
    'SHORT_ANSWER',
    'SENTENCE_COMPLETION',
    'FORM_COMPLETION',
    'NOTE_COMPLETION',
    'TABLE_COMPLETION',
    'FLOW_CHART_COMPLETION',
    'SUMMARY_COMPLETION',
    'MAP_LABELING',
    'PLAN_LABELING',
    'DIAGRAM_LABELING',
    'FILL_BLANK',
  ],
  READING: [
    'MULTIPLE_CHOICE',
    'TRUE_FALSE_NG',
    'SHORT_ANSWER',
    'SENTENCE_COMPLETION',
    'MATCHING',
    'MATCHING_HEADINGS',
    'FORM_COMPLETION',
    'NOTE_COMPLETION',
    'TABLE_COMPLETION',
    'FLOW_CHART_COMPLETION',
    'SUMMARY_COMPLETION',
    'DIAGRAM_LABELING',
    'FILL_BLANK',
  ],
  WRITING: ['WRITING_TASK1', 'WRITING_TASK2'],
  SPEAKING: ['SPEAKING_PART1', 'SPEAKING_PART2', 'SPEAKING_PART3'],
};

function isAllowed(moduleType, questionType) {
  const list = ALLOWED_BY_MODULE[moduleType];
  return Array.isArray(list) && list.includes(questionType);
}

module.exports = { ALL_QUESTION_TYPES, MODULE_TYPES, ALLOWED_BY_MODULE, isAllowed };
